version: "3.4"


services:
  plex:
    image: plexinc/pms-docker:1.19.3.2852-219a9974e
    container_name: plex
    hostname: babushka.engineroom.middlearth.lan
    restart: unless-stopped
    network_mode: host # only needed on first run/boot
    environment:
      - "ADVERTISE_IP=http://192.168.88.1:32400/"
      - "ALLOWED_NETWORKS=192.168.88.0/24,192.168.1.0/24"
      - "PLEX_GID=1000"
      - "PLEX_UID=1000"
      - "TZ=Europe/Berlin"
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      - "32400:32400/udp"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      - "32469:32469/udp"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for controlling Plex for Roku via Plex Companion
      - "8324:8324"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "/mnt/storage/containers/plex/config:/config"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/movies:/movies"
    labels:
      org.label-schema.group: "content"


  transmission:
    image: haugene/transmission-openvpn:2.14
    container_name: transmission
    restart: unless-stopped
    privileged: true
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "${OPENVPN_PROVIDER}_COUNTRY=${OPENVPN_COUNTRY}"
      - "OPENVPN_PROVIDER=${OPENVPN_PROVIDER}"
      - "OPENVPN_USERNAME=${OPENVPN_USERNAME}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - "OPENVPN_OPTS=--replay-window 64 30 --mute-replay-warnings --inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping"
      - "LOCAL_NETWORK=192.168.88.0/24"
      - "TRANSMISSION_RATIO_LIMIT_ENABLED=true"
      - "TRANSMISSION_RATIO_LIMIT=1.5"
      - "TRANSMISSION_WEB_UI=combustion"
    ports:
      - "9091:9091"
    volumes:
      - "/mnt/storage/containers/transmission/data:/data"
      - "/mnt/storage/media/videos/movies:/movies"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      org.label-schema.group: "content"


  medusa:
    image: linuxserver/medusa:v0.3.16-ls50
    container_name: medusa
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/storage/containers/medusa/config:/config"
      - "/mnt/storage/containers/medusa/downloads:/downloads"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "./post-processing.sh:/post-processing.sh"
      - "/mnt/storage/media/videos/tv:/tv"
    labels:
      org.label-schema.group: "content"


  calibre-web:
    image: linuxserver/calibre-web:V0.6.4-ls27
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8083:8083"
    volumes:
      - "/mnt/storage/containers/calibre-web/config:/config"
      - "/mnt/storage/documents/ebooks/calibre-library:/books:ro"
    labels:
      org.label-schema.group: "content"


  tautulli:
    image: tautulli/tautulli@sha256:3094c7e5758e82893e6a5ff948a5e6bba364c343939f54f78a1e7c75145b1d12
    container_name: tautulli
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8181:8181"
    volumes:
      - "/mnt/storage/containers/tautulli/config:/config"
      - "/mnt/storage/containers/plex/config/Library/Application Support/Plex Media Server/Logs/:/plex_logs:ro"
    labels:
      org.label-schema.group: "content"
