version: "3.4"



volumes:
  acme:
  nginx-conf:
  nginx-html:
  nginx-ssl-certs:
  nginx-vhostd:



networks:
  monitor-net:
    driver: bridge



services:
  # ┏┓      
  # ┃ ┏┓┏┓┏┓
  # ┗┛┗┛┛ ┗ 

  smtp:
    image: namshi/smtp@sha256:aa63b8de68ce63dfcf848c56f3c1a16d81354f4accd4242a0086c57dd5a91d77
    container_name: smtp
    restart: unless-stopped
    environment:
      - "GMAIL_USER=${SMTP_GMAIL_USER}"
      - "GMAIL_PASSWORD=${SMTP_GMAIL_PASSWORD}"
      - "MAILNAME=${SMTP_MAILNAME}"
      - "TZ=Europe/Berlin"
    ports:
      - "25:25"
    labels:
      org.label-schema.group: "services"


  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.2-alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-ssl-certs:/etc/nginx/certs:ro"
      - "nginx-vhostd:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-letsencrypt:
    image: nginxproxy/acme-companion:2.1.0
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    environment:
      - "NGINX_PROXY_CONTAINER=nginx-proxy"
      - "DEFAULT_EMAIL=${EMAIL_ADDRESS}"
    volumes:
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-ssl-certs:/etc/nginx/certs"
      - "nginx-vhostd:/etc/nginx/vhost.d"
      - "acme:/etc/acme.sh"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-public:
    image: nginx:1.17.2-alpine
    container_name: nginx-public
    restart: unless-stopped
    volumes:
      - "./nginx-public.conf:/etc/nginx/nginx.conf:ro"
      - "./index-public.html:/usr/share/nginx/html/index.html"
    environment:
      - "VIRTUAL_HOST=public.${DOMAIN_NAME}"
      - "LETSENCRYPT_HOST=public.${DOMAIN_NAME}"
      - "LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}"
    labels:
      org.label-schema.group: "proxies"


  oauth2-proxy:
    image: a5huynh/oauth2_proxy@sha256:4a3cc343dde63325ebce980eda25f7458c343f94dac34089c7d0122158ab3119
    container_name: oauth2-proxy
    restart: unless-stopped
    command:
      - --authenticated-emails-file=/authenticated-emails.conf
      - --client-id=${OAUTH2_CLIENT_ID}
      - --client-secret=${OAUTH2_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --footer=private.${DOMAIN_NAME} is protected with oauth2
      - --http-address=0.0.0.0:4180
      - --upstream=http://nginx-private
    environment:
      - "VIRTUAL_HOST=private.${DOMAIN_NAME},calibre.private.${DOMAIN_NAME},mikrotik.private.${DOMAIN_NAME},medusa.private.${DOMAIN_NAME},transmission.private.${DOMAIN_NAME},fava.private.${DOMAIN_NAME}"
      - "VIRTUAL_PORT=4180"
      - "LETSENCRYPT_HOST=private.${DOMAIN_NAME},calibre.private.${DOMAIN_NAME},mikrotik.private.${DOMAIN_NAME},medusa.private.${DOMAIN_NAME},transmission.private.${DOMAIN_NAME},fava.private.${DOMAIN_NAME}"
      - "LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}"
    volumes:
      - "./authenticated-emails.conf:/authenticated-emails.conf:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-private:
    image: nginx:1.17.2-alpine
    container_name: nginx-private
    restart: unless-stopped
    volumes:
      - "./nginx-private.conf:/etc/nginx/nginx.conf:ro"
      - "./index-private.html:/usr/share/nginx/html/index.html"
    labels:
      org.label-schema.group: "proxies"


  samba:
    image: dperson/samba@sha256:ea7268d6f3b39e1647f88578c700735568eba3fedf84d89c6e060dccb2ed2c78
    container_name: samba
    restart: unless-stopped
    entrypoint:
      - samba.sh
      # -u
      # - "<username;password>[;id;group-id/group-name]"
      - -u
      - "${SAMBA_USER1}"
      - -u
      - "${SAMBA_USER2}"
      # -s
      # - "<name;/path>[;browse;readonly;guest;users;admins;wl]"
      - -s
      - "storage;/storage;yes;yes;no;all;cewood;cewood"
      # - -s
      # - "backup;/backup;yes;yes;no;all;cewood;cewood"
    environment:
      - "NMBD=true"
      - "WORKGROUP=middlearth"
      - "TZ=Europe/Berlin"
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      # - "/mnt/backup1:/backup"
      - "/mnt/storage:/storage"
    labels:
      org.label-schema.group: "services"


  syncthing:
    image: syncthing/syncthing:1.27
    container_name: syncthing
    restart: unless-stopped
    environment:
      - "TZ=Europe/Berlin"
      - "PUID=1000"
      - "PGID=1000"
      - "VIRTUAL_HOST=syncthing.engineroom.middlearth.lan"
      - "VIRTUAL_PORT=8384"
      - "VIRTUAL_PROTO=https"
    ports:
      - "8384:8384" # Web UI
      - "22000:22000/tcp" # TCP file transfers
      - "22000:22000/udp" # QUIC file transfers
      - "21027:21027/udp" # Receive local discovery broadcasts
    volumes:
      - "/mnt/storage/containers/syncthing/config:/var/syncthing/config"
      - "/mnt/storage/containers/syncthing/data/self:/sync/self"
      - "/mnt/storage/containers/syncthing/data:/sync"
    labels:
      org.label-schema.group: "backups"


  mbsync:
    image: cewood/mbsync:alpine_8da26a4
    container_name: mbsync
    working_dir: /workdir
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "/mnt/storage/containers/mbsync/data:/workdir/data"
      - "./mbsync/mbsyncrc:/workdir/.mbsyncrc"
      - "./mbsync/crontab:/etc/crontab"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "backups"


  rclone:
    image: cewood/rclone:alpine_7bdc646
    container_name: rclone
    working_dir: /data
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "/mnt/storage/containers/rclone/conf:/conf"
      - "/mnt/storage/containers/rclone/data:/data"
      - "./rclone/rclone.conf:/conf/rclone/rclone.conf"
      - "./rclone/crontab:/conf/crontab"
    restart: unless-stopped
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "backups"


  # ┳┳┓   ┓•  
  # ┃┃┃┏┓┏┫┓┏┓
  # ┛ ┗┗ ┗┻┗┗┻

  plex:
    image: plexinc/pms-docker:1.40.2.8395-c67dce28e
    container_name: plex
    hostname: babushka.engineroom.middlearth.lan
    restart: unless-stopped
    network_mode: host # only needed on first run/boot
    environment:
      - "ADVERTISE_IP=http://192.168.88.1:32400/"
      - "ALLOWED_NETWORKS=192.168.88.0/24,192.168.1.0/24"
      - "PLEX_GID=1000"
      - "PLEX_UID=1000"
      - "TZ=Europe/Berlin"
      - "VIRTUAL_HOST=plex.engineroom.middlearth.lan"
      - "VIRTUAL_PORT=32400"
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      - "32400:32400/udp"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      - "32469:32469/udp"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for controlling Plex for Roku via Plex Companion
      - "8324:8324"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "/mnt/storage/containers/plex/config:/config"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/movies:/movies"
    labels:
      org.label-schema.group: "content"


  transmission:
    image: haugene/transmission-openvpn:5.3.1
    container_name: transmission
    restart: unless-stopped
    privileged: true
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "${OPENVPN_PROVIDER}_COUNTRY=${OPENVPN_COUNTRY}"
      - "OPENVPN_PROVIDER=${OPENVPN_PROVIDER}"
      - "OPENVPN_USERNAME=${OPENVPN_USERNAME}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - "OPENVPN_OPTS=--replay-window 64 30 --mute-replay-warnings --inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping"
      - "LOCAL_NETWORK=192.168.88.0/24"
      - "TRANSMISSION_RATIO_LIMIT_ENABLED=true"
      - "TRANSMISSION_RATIO_LIMIT=1.5"
      - "TRANSMISSION_WEB_UI=combustion"
      - "VIRTUAL_HOST=transmission.engineroom.middlearth.lan"
      - "VIRTUAL_PORT=9091"
    ports:
      - "9091:9091"
    volumes:
      - "/mnt/storage/containers/transmission/data:/data"
      - "/mnt/storage/media/videos/movies:/movies"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      org.label-schema.group: "content"


  medusa:
    image: linuxserver/medusa:1.0.21
    container_name: medusa
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "VIRTUAL_HOST=medusa.engineroom.middlearth.lan"
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/storage/containers/medusa/config:/config"
      - "/mnt/storage/containers/medusa/downloads:/downloads"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "./post-processing.sh:/post-processing.sh"
      - "/mnt/storage/media/videos/tv:/tv"
    labels:
      org.label-schema.group: "content"


  calibre-web:
    image: linuxserver/calibre-web:V0.6.21
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "VIRTUAL_HOST=calibre.engineroom.middlearth.lan"
    ports:
      - "8083:8083"
    volumes:
      - "/mnt/storage/containers/calibre-web/config:/config"
      - "/mnt/storage/documents/ebooks/calibre-library:/books:ro"
    labels:
      org.label-schema.group: "content"


  prowlarr:
    image: linuxserver/prowlarr:version-1.1.3.2521
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "VIRTUAL_HOST=prowlarr.engineroom.middlearth.lan"
    volumes:
      - "/mnt/storage/containers/prowlarr/config:/config"
    ports:
      - "9696:9696"
    labels:
      org.label-schema.group: "content"


  # ┳┳┓•  
  # ┃┃┃┓┏┏
  # ┛ ┗┗┛┗

  fava:
    image: yegle/fava:version-1.15
    container_name: fava
    restart: always
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Europe/Berlin"
      - "BEANCOUNT_FILE=/bean/main.bean"
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/storage/containers/syncthing/data/schrodinger/code/src/github.com/cewood/finances-ledger:/bean:ro"
    labels:
      org.label-schema.group: "content"


  # ┳┳┓    •     •    
  # ┃┃┃┏┓┏┓┓╋┏┓┏┓┓┏┓┏┓
  # ┛ ┗┗┛┛┗┗┗┗┛┛ ┗┛┗┗┫
  #                  ┛

  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    environment:
      - "TZ=Europe/Berlin"
      - "VIRTUAL_HOST=prometheus.engineroom.middlearth.lan"
    volumes:
      - "./monitoring/prometheus:/etc/prometheus"
      - "/mnt/storage/containers/prometheus/data:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=90d'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  alertmanager:
    image: prom/alertmanager:v0.23.0
    container_name: alertmanager
    environment:
      - "VIRTUAL_HOST=alertmanager.engineroom.middlearth.lan"
    volumes:
      - "./monitoring/alertmanager/config.yml:/etc/alertmanager/config.yml"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - "9093:9093"
    expose:
      - 9093
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  blackbox-exporter:
    image: prom/blackbox-exporter:v0.19.0
    container_name: blackbox-exporter
    volumes:
      - "./monitoring/blackbox-exporter/config.yml:/etc/blackbox-exporter/config.yml"
    command:
      - '--config.file=/etc/blackbox-exporter/config.yml'
    restart: unless-stopped
    ports:
      - "9115:9115"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  speedtest-exporter:
    image: cewood/prometheus-speedtest-exporter:v1.0.0
    container_name: speedtest-exporter
    restart: unless-stopped
    ports:
      - "9469:9469"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.4
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  grafana:
    image: grafana/grafana:8.4.1
    container_name: grafana
    volumes:
      - "/mnt/storage/containers/grafana/data:/var/lib/grafana"
      - "./monitoring/grafana/provisioning:/etc/grafana/provisioning"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      - "VIRTUAL_HOST=grafana.engineroom.middlearth.lan"
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  pushgateway:
    image: prom/pushgateway:v1.4.2
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - 9092:9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

