version: "3.4"
networks:
  monitor-net:
    driver: bridge

volumes:
  nginx-conf:
  nginx-html:
  nginx-ssl-certs:
  nginx-vhostd:


services:
  smtp:
    image: namshi/smtp@sha256:aa63b8de68ce63dfcf848c56f3c1a16d81354f4accd4242a0086c57dd5a91d77
    container_name: smtp
    restart: unless-stopped
    environment:
      - "GMAIL_USER=${SMTP_GMAIL_USER}"
      - "GMAIL_PASSWORD=${SMTP_GMAIL_PASSWORD}"
      - "MAILNAME=${SMTP_MAILNAME}"
      - "TZ=Europe/Berlin"
    ports:
      - "25:25"
    labels:
      org.label-schema.group: "services"


  nginx-proxy:
    image: jwilder/nginx-proxy:alpine-0.7.0
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy
    volumes:
      - "nginx-conf:/etc/nginx/conf.d"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-ssl-certs:/etc/nginx/certs:ro"
      - "nginx-vhostd:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.12.1
    container_name: nginx-letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-ssl-certs:/etc/nginx/certs"
      - "nginx-vhostd:/etc/nginx/vhost.d"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-public:
    image: nginx:1.17.2-alpine
    container_name: nginx-public
    restart: unless-stopped
    volumes:
      - "./nginx-public.conf:/etc/nginx/nginx.conf:ro"
      - "./index-public.html:/usr/share/nginx/html/index.html"
    environment:
      - "VIRTUAL_HOST=public.${DOMAIN_NAME}"
      - "LETSENCRYPT_HOST=public.${DOMAIN_NAME}"
      - "LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}"
    labels:
      org.label-schema.group: "proxies"


  oauth2-proxy:
    image: a5huynh/oauth2_proxy@sha256:4a3cc343dde63325ebce980eda25f7458c343f94dac34089c7d0122158ab3119
    container_name: oauth2-proxy
    restart: unless-stopped
    command:
      - --authenticated-emails-file=/authenticated-emails.conf
      - --client-id=${OAUTH2_CLIENT_ID}
      - --client-secret=${OAUTH2_CLIENT_SECRET}
      - --cookie-secret=${OAUTH2_COOKIE_SECRET}
      - --footer=private.${DOMAIN_NAME} is protected with oauth2
      - --http-address=0.0.0.0:4180
      - --upstream=http://nginx-private
    environment:
      - "VIRTUAL_HOST=private.${DOMAIN_NAME},calibre.private.${DOMAIN_NAME},mikrotik.private.${DOMAIN_NAME},medusa.private.${DOMAIN_NAME},transmission.private.${DOMAIN_NAME},moinmoin.private.${DOMAIN_NAME},fava.private.${DOMAIN_NAME}"
      - "VIRTUAL_PORT=4180"
      - "LETSENCRYPT_HOST=private.${DOMAIN_NAME},calibre.private.${DOMAIN_NAME},mikrotik.private.${DOMAIN_NAME},medusa.private.${DOMAIN_NAME},transmission.private.${DOMAIN_NAME},moinmoin.private.${DOMAIN_NAME},fava.private.${DOMAIN_NAME}"
      - "LETSENCRYPT_EMAIL=${EMAIL_ADDRESS}"
    volumes:
      - "./authenticated-emails.conf:/authenticated-emails.conf:ro"
    labels:
      org.label-schema.group: "proxies"


  nginx-private:
    image: nginx:1.17.2-alpine
    container_name: nginx-private
    restart: unless-stopped
    volumes:
      - "./nginx-private.conf:/etc/nginx/nginx.conf:ro"
      - "./index-private.html:/usr/share/nginx/html/index.html"
    labels:
      org.label-schema.group: "proxies"


  samba:
    image: dperson/samba@sha256:ea7268d6f3b39e1647f88578c700735568eba3fedf84d89c6e060dccb2ed2c78
    container_name: samba
    restart: unless-stopped
    entrypoint:
      - samba.sh
      # -u
      # - "<username;password>[;id;group-id/group-name]"
      - -u
      - "${SAMBA_USER1}"
      - -u
      - "${SAMBA_USER2}"
      # -s
      # - "<name;/path>[;browse;readonly;guest;users;admins;wl]"
      - -s
      - "storage;/storage;yes;yes;no;all;cewood;cewood"
      # - -s
      # - "backup;/backup;yes;yes;no;all;cewood;cewood"
    environment:
      - "NMBD=true"
      - "WORKGROUP=middlearth"
      - "TZ=Europe/Berlin"
    ports:
      - "139:139"
      - "445:445"
      - "137:137/udp"
      - "138:138/udp"
    volumes:
      # - "/mnt/backup1:/backup"
      - "/mnt/storage:/storage"
    labels:
      org.label-schema.group: "services"


  syncthing:
    image: linuxserver/syncthing:v1.5.0-ls34
    container_name: syncthing
    restart: unless-stopped
    network_mode: host
    environment:
      - "TZ=Europe/Berlin"
      - "PUID=1000"
      - "PGID=1000"
    ports:
      - "8384:8384"
      - "21027:21027/udp"
      - "22000:22000"
    volumes:
      - "/mnt/storage/containers/syncthing/config:/config"
      - "/mnt/storage/containers/syncthing/data/self:/sync/self"
      - "/mnt/storage/containers/syncthing/data:/sync"
    labels:
      org.label-schema.group: "backups"


  plex:
    image: plexinc/pms-docker:1.19.3.2852-219a9974e
    container_name: plex
    hostname: babushka.engineroom.middlearth.lan
    restart: unless-stopped
    network_mode: host # only needed on first run/boot
    environment:
      - "ADVERTISE_IP=http://192.168.88.1:32400/"
      - "ALLOWED_NETWORKS=192.168.88.0/24,192.168.1.0/24"
      - "PLEX_GID=1000"
      - "PLEX_UID=1000"
      - "TZ=Europe/Berlin"
    ports:
      # for access to the Plex Media Server [required]
      - "32400:32400"
      - "32400:32400/udp"
      # for access to the Plex DLNA Server
      - "1900:1900/udp"
      - "32469:32469"
      - "32469:32469/udp"
      # for controlling Plex Home Theater via Plex Companion
      - "3005:3005"
      # for older Bonjour/Avahi network discovery
      - "5353:5353/udp"
      # for controlling Plex for Roku via Plex Companion
      - "8324:8324"
      # for current GDM network discovery
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    volumes:
      - "/mnt/storage/containers/plex/config:/config"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/movies:/movies"
    labels:
      org.label-schema.group: "content"


  transmission:
    image: haugene/transmission-openvpn:2.14
    container_name: transmission
    restart: unless-stopped
    privileged: true
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "${OPENVPN_PROVIDER}_COUNTRY=${OPENVPN_COUNTRY}"
      - "OPENVPN_PROVIDER=${OPENVPN_PROVIDER}"
      - "OPENVPN_USERNAME=${OPENVPN_USERNAME}"
      - "OPENVPN_PASSWORD=${OPENVPN_PASSWORD}"
      - "OPENVPN_OPTS=--replay-window 64 30 --mute-replay-warnings --inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping"
      - "LOCAL_NETWORK=192.168.88.0/24"
      - "TRANSMISSION_RATIO_LIMIT_ENABLED=true"
      - "TRANSMISSION_RATIO_LIMIT=1.5"
      - "TRANSMISSION_WEB_UI=combustion"
    ports:
      - "9091:9091"
    volumes:
      - "/mnt/storage/containers/transmission/data:/data"
      - "/mnt/storage/media/videos/movies:/movies"
      - "/mnt/storage/media/videos/misc:/misc"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "/mnt/storage/media/videos/tv:/tv"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      org.label-schema.group: "content"


  medusa:
    image: linuxserver/medusa:v0.3.16-ls50
    container_name: medusa
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8081:8081"
    volumes:
      - "/mnt/storage/containers/medusa/config:/config"
      - "/mnt/storage/containers/medusa/downloads:/downloads"
      - "/mnt/storage/media/videos/sickrage:/sickrage"
      - "./post-processing.sh:/post-processing.sh"
      - "/mnt/storage/media/videos/tv:/tv"
    labels:
      org.label-schema.group: "content"


  calibre-web:
    image: linuxserver/calibre-web:V0.6.4-ls27
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8083:8083"
    volumes:
      - "/mnt/storage/containers/calibre-web/config:/config"
      - "/mnt/storage/documents/ebooks/calibre-library:/books:ro"
    labels:
      org.label-schema.group: "content"


  tautulli:
    image: tautulli/tautulli@sha256:3094c7e5758e82893e6a5ff948a5e6bba364c343939f54f78a1e7c75145b1d12
    container_name: tautulli
    restart: unless-stopped
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
    ports:
      - "8181:8181"
    volumes:
      - "/mnt/storage/containers/tautulli/config:/config"
      - "/mnt/storage/containers/plex/config/Library/Application Support/Plex Media Server/Logs/:/plex_logs:ro"
    labels:
      org.label-schema.group: "content"


  unifi:
    image: "jacobalberty/unifi:6.0.28"
    container_name: unifi
    restart: unless-stopped
    ports:
      - "3478:3478/udp" # STUN
      - "6789:6789/tcp" # Speed test
      - "8080:8080/tcp" # Device/ controller comm.
      - "8443:8443/tcp" # Controller GUI/API as seen in a web browser
      - "8880:8880/tcp" # HTTP portal redirection
      - "8843:8843/tcp" # HTTPS portal redirection
      - "10001:10001/udp" # AP discovery
    volumes:
      - "/mnt/storage/containers/unifi/data:/unifi"
    labels:
      org.label-schema.group: "services"


  filebrowser:
    image: filebrowser/filebrowser:v2.3.0
    container_name: filebrowser
    restart: always
    environment:
      - "PUID=1000"
      - "PGID=1000"
      - "TZ=Europe/Berlin"
      - "FB_NOAUTH=1"
      - "FB_PERM_DELETE=0"
      - "FB_PERM_ADMIN=0"
    ports:
      - "8084:80"
    volumes:
      - "/mnt/storage:/srv/storage:ro"
      - "/mnt/backup:/srv/backup:ro"
    labels:
      org.label-schema.group: "backups"


  mbsync:
    image: cewood/mbsync:alpine_8da26a4
    container_name: mbsync
    working_dir: /workdir
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "/mnt/storage/containers/mbsync/data:/workdir/data"
      - "./mbsync/mbsyncrc:/workdir/.mbsyncrc"
      - "./mbsync/crontab:/etc/crontab"
    restart: unless-stopped
    labels:
      org.label-schema.group: "backups"


  moinmoin:
    image: olavgg/moinmoin-wiki:1.9.10.1
    container_name: moinmoin
    restart: always
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Europe/Berlin"
      - "NOSSL=1"
    ports:
      - "8082:80"
      - "4443:443"
    volumes:
      - "/mnt/storage/containers/moinmoin/data:/usr/local/share/moin/data"
      - "./wikiconfig.py:/usr/local/share/moin/wikiconfig.py"
      - "./wiki-logo.png:/usr/local/lib/python2.7/dist-packages/MoinMoin/web/static/htdocs/common/logo.png"
    labels:
      org.label-schema.group: "content"


  fava:
    image: yegle/fava:version-1.15
    container_name: fava
    restart: always
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Europe/Berlin"
      - "BEANCOUNT_FILE=/bean/main.bean"
    ports:
      - "5000:5000"
    volumes:
      - "/mnt/storage/containers/syncthing/data/schrodinger/code/src/github.com/cewood/finances-ledger:/bean:ro"
    labels:
      org.label-schema.group: "content"


  glances:
    image: nicolargo/glances@sha256:48b1577cbb8b62bf760ee29822324fa4b970f7dcf5ae253ec8123f6adbfa930f
    container_name: glances
    restart: always
    pid: host
    environment:
      - "UID=1000"
      - "GID=1000"
      - "TZ=Europe/Berlin"
      - "GLANCES_OPT=-w"
    ports:
      - "61208:61208"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/mnt/storage:/mnt/storage:ro"
      - "/mnt/backup:/mnt/backup:ro"
    labels:
      org.label-schema.group: "monitoring"


  prometheus:
    image: prom/prometheus:v2.23.0
    container_name: prometheus
    environment:
      - "TZ=Europe/Berlin"
    volumes:
      - "./monitoring/prometheus:/etc/prometheus"
      - "/mnt/storage/containers/prometheus/data:/prometheus"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - "./monitoring/alertmanager/config.yml:/etc/alertmanager/config.yml"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    ports:
      - "9093:9093"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  nodeexporter:
    image: prom/node-exporter:v1.0.1
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.38.4
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /cgroup:/cgroup:ro
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  grafana:
    image: grafana/grafana:7.3.4
    container_name: grafana
    volumes:
      - "/mnt/storage/containers/grafana/data:/var/lib/grafana"
      - "./monitoring/dockprom/grafana/provisioning:/etc/grafana/provisioning"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"


  pushgateway:
    image: prom/pushgateway:v1.3.0
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"
