# dev-sec.ansible-ssh-hardening
- src: https://github.com/dev-sec/ansible-ssh-hardening
  version: 5.0.0
  name: dev-sec.ansible-ssh-hardening

# dev-sec.ansible-os-hardening
- src: https://github.com/dev-sec/ansible-os-hardening
  version: 5.0.0
  name: dev-sec.ansible-os-hardening

# angstwad.docker_ubuntu
- src: https://github.com/angstwad/docker.ubuntu
  version: v3.6.2
  name: angstwad.docker_ubuntu
