---
# defaults file for babushka
mounts:
  - source: UUID=0cb445cc-92cb-4d6c-b6f0-62b334486315
    path: /mnt/storage
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=30
  - source: UUID=1986aad1-e95c-4c1c-af3e-019703260e1b
    path: /mnt/backup
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=30,x-systemd.idle-timeout=1800
  - source: UUID=da2628f8-79c6-417a-8e90-861108b60c61
    path: /mnt/backup2
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=30,x-systemd.idle-timeout=1800
services:
  - name: rsnapshot-sync
    description: Rsnapshot-sync
    dependencies:
      - Require=rsnapshot-weekly.service
      - After=rsnapshot-weekly.service
    calendar: "*-*-* 00:00:00"
    command: /root/rsnapprereq sync /proc/stat /var/run/rsnapshot-target-sync
  - name: rsnapshot-daily
    description: Rsnapshot-daily
    dependencies:
      - Require=rsnapshot-sync
      - After=rsnapshot-sync.service
    calendar: "*-*-* 00:00:00"
    command: /root/rsnapprereq daily /var/run/rsnapshot-target-sync /var/run/rsnapshot-target-daily
  - name: rsnapshot-weekly
    description: Rsnapshot-weekly
    dependencies:
      - Require=rsnapshot-monthly.service
      - After=rsnapshot-monthly.service
    calendar: "Sun *-*-* 00:00:00"
    command: /root/rsnapprereq weekly /var/run/rsnapshot-target-daily /var/run/rsnapshot-target-weekly
  - name: rsnapshot-monthly
    description: Rsnapshot-monthly
    calendar: "*-*-01 00:00:00"
    command: /root/rsnapprereq monthly /var/run/rsnapshot-target-weekly /var/run/rsnapshot-target-monthly
compose_project_name: "babuskha"
domain_name: "{{ vault_domain_name | trim }}"
email_address: "{{ vault_email_address | trim }}"
#gmvault_email_address: "{{ vault_gmvault_email_address | trim }}" #todelete
#letsencrypt_email: "{{ vault_letsencrypt_email | trim }}" #todelete
#letsencrypt_host_public: "{{ vault_letsencrypt_host_public | trim }}" #todelete
#nginx_server_name_public: "{{ vault_nginx_server_name_public | trim }}" #todelete
oauth2_client_id: "{{ vault_oauth2_client_id | trim }}"
oauth2_client_secret: "{{ vault_oauth2_client_secret | trim }}"
oauth2_cookie_secret: "{{ vault_oauth2_cookie_secret | trim }}"
openvpn_config: "{{ vault_openvpn_config | trim }}"
openvpn_password: "{{ vault_openvpn_password | trim }}"
openvpn_provider: "{{ vault_openvpn_provider | trim }}"
openvpn_username: "{{ vault_openvpn_username | trim }}"
#plex_login: "{{ vault_plex_login | trim }}" #todelete
#plex_password: "{{ vault_plex_password | trim }}" #todelete
radarr_apikey: "{{ vault_radarr_apikey | trim }}"
samba_user1: "{{ vault_samba_user1 | trim }}"
samba_user2: "{{ vault_samba_user2 | trim }}"
smtp_gmail_user: "{{ vault_smtp_gmail_user | trim }}"
smtp_gmail_password: "{{ vault_smtp_gmail_password | trim }}"
smtp_hostname: "{{ vault_smtp_hostname | trim }}"
smtp_mailname: "{{ vault_smtp_mailname | trim }}"
#virtual_host_public: "{{ vault_virtual_host_public | trim }}"
