---
# defaults file for babushka
mounts:
  - source: UUID=4b8b3527-618c-416c-8f21-a232d750fdae
    path: /mnt/storage
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=30
  - source: UUID=bd1d7435-d413-49dd-be44-c7f18ea1bb49
    path: /mnt/backup
    opts: noauto,x-systemd.automount,x-systemd.device-timeout=30,x-systemd.idle-timeout=1800
services:
  - name: rsnapshot-sync
    description: Rsnapshot-sync
    dependencies:
      - Require=rsnapshot-weekly.service
      - After=rsnapshot-weekly.service
    calendar: "*-*-* 00:00:00"
    command: /root/rsnapprereq sync /proc/stat /var/run/rsnapshot-target-sync
  - name: rsnapshot-daily
    description: Rsnapshot-daily
    dependencies:
      - Require=rsnapshot-sync
      - After=rsnapshot-sync.service
    calendar: "*-*-* 00:00:00"
    command: /root/rsnapprereq daily /var/run/rsnapshot-target-sync /var/run/rsnapshot-target-daily
  - name: rsnapshot-weekly
    description: Rsnapshot-weekly
    dependencies:
      - Require=rsnapshot-monthly.service
      - After=rsnapshot-monthly.service
    calendar: "Sun *-*-* 00:00:00"
    command: /root/rsnapprereq weekly /var/run/rsnapshot-target-daily /var/run/rsnapshot-target-weekly
  - name: rsnapshot-monthly
    description: Rsnapshot-monthly
    calendar: "*-*-01 00:00:00"
    command: /root/rsnapprereq monthly /var/run/rsnapshot-target-weekly /var/run/rsnapshot-target-monthly
compose_project_name: "babuskha"
domain_name: "{{ vault_domain_name | trim }}"
email_address: "{{ vault_email_address | trim }}"
oauth2_client_id: "{{ vault_oauth2_client_id | trim }}"
oauth2_client_secret: "{{ vault_oauth2_client_secret | trim }}"
oauth2_cookie_secret: "{{ vault_oauth2_cookie_secret | trim }}"
openvpn_config: "{{ vault_openvpn_config | trim }}"
openvpn_password: "{{ vault_openvpn_password | trim }}"
openvpn_provider: "{{ vault_openvpn_provider | trim }}"
openvpn_username: "{{ vault_openvpn_username | trim }}"
radarr_apikey: "{{ vault_radarr_apikey | trim }}"
samba_user1: "{{ vault_samba_user1 | trim }}"
samba_user2: "{{ vault_samba_user2 | trim }}"
smtp_gmail_password: "{{ vault_smtp_gmail_password | trim }}"
smtp_gmail_user: "{{ vault_smtp_gmail_user | trim }}"
smtp_hostname: "{{ vault_smtp_hostname | trim }}"
smtp_mailname: "{{ vault_smtp_mailname | trim }}"
