galaxy_info:
  author: 
  description: Host specific role for Babushka
  company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: GPLv3

  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - { role: local.ssh-authorised-keys,
      tags: [
        "ssh",
        "authorised-keys"
      ]
    }
  - { role: local.sshd-banner,
      tags: [
        "ssh",
        "banner"
      ]
    }
  - { role: local.papertrail-logging,
      tags: [
        "logging",
        "papertrail"
      ]
    }
  - { role: dev-sec.ansible-ssh-hardening,
      os_auth_lockout_time: 60,
      os_auth_pam_passwdqc_enable: false,
      sftp_enabled: true,
      ssh_allow_agent_forwarding: true,
      ssh_allow_tcp_forwarding: true,
      ssh_banner: true,
      ssh_max_auth_retries: 5,  # should we remove this, i have too many keys :(
      ssh_use_pam: true,  # to allow login via locked accounts, i.e. no passwords 
      tags: [
        "ssh",
        "security",
        "dev-sec"
      ]
    }
  - { role: dev-sec.ansible-os-hardening,
      tags: [
        "os",
        "security",
        "dev-sec"
      ]
    }
  - { role: angstwad.docker_ubuntu,
      become: yes,
      docker_apt_channel: edge,
      tags: [
        "docker",
      ]
    }
