galaxy_info:
  author: Cameron Wood
  description: Private host specific role for Babushka

  license: MIT

  min_ansible_version: 2.9

  platforms:
  - name: Ubuntu
    versions:
    - all

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - { role: local.ssh-authorised-keys,
      tags: [
        "local.ssh-authorised-keys"
      ]
    }

  - { role: local.sshd-banner,
      tags: [
        "local.sshd-banner"
      ]
    }

  - { role: local.papertrail-logging,
      tags: [
        "local.papertrail-logging"
      ]
    }

  - { role: local.docker-compose,
      compose_project_name: "babuskha",
      authenticated_emails: "{{ vault_authenticated_emails | trim }}",
      domain_name:          "{{ vault_domain_name | trim }}",
      email_address:        "{{ vault_email_address | trim }}",
      mbsync_account:       "{{ vault_mbsync_account | trim }}",
      mbsync_password:      "{{ vault_mbsync_password | trim }}",
      oauth2_client_id:     "{{ vault_oauth2_client_id | trim }}",
      oauth2_client_secret: "{{ vault_oauth2_client_secret | trim }}",
      oauth2_cookie_secret: "{{ vault_oauth2_cookie_secret | trim }}",
      openvpn_country:      "{{ vault_openvpn_country | trim }}",
      openvpn_password:     "{{ vault_openvpn_password | trim }}",
      openvpn_provider:     "{{ vault_openvpn_provider | trim }}",
      openvpn_username:     "{{ vault_openvpn_username | trim }}",
      radarr_apikey:        "{{ vault_radarr_apikey | trim }}",
      samba_user1:          "{{ vault_samba_user1 | trim }}",
      samba_user2:          "{{ vault_samba_user2 | trim }}",
      smtp_gmail_password:  "{{ vault_smtp_gmail_password | trim }}",
      smtp_gmail_user:      "{{ vault_smtp_gmail_user | trim }}",
      smtp_hostname:        "{{ vault_smtp_hostname | trim }}",
      smtp_mailname:        "{{ vault_smtp_mailname | trim }}",
      tags: [
        "local.docker-compose"
      ]
    }

  - { role: local.module.rsnapshot,
      backups: [
        { name: default,
          enabled: true,
          snapshot_root: /mnt/backup,
          retain_settings: [
            { name: "daily",
              count: 7,
              schedule: "Tue..Sun *-*-* 1:00:00",
              execs_entries: [
                "daily"
              ],
            },
            { name: "weekly",
              count: 4,
              schedule: "Mon *-*-8..31 1:00:00",
              execs_entries: [
                "weekly",
                "daily"
              ],
            },
            { name: "monthly",
              count: 6,
              schedule: "Mon *-2..12-1..7 1:00:00",
              execs_entries: [
                "monthly",
                "weekly",
                "daily"
              ],
            },
            { name: "yearly",
              count: 1,
              schedule: "Mon *-1-1..7 1:00:00",
              execs_entries: [
                "yearly",
                "monthly",
                "weekly",
                "daily"
              ],
            }
          ],
          backup_directives: [
            "backup	/mnt/storage/code	babushka/",
            "backup	/mnt/storage/containers/mbsync/data	babushka/mbsync_data",
            "backup	/mnt/storage/containers/medusa/config	babushka/medusa_config",
            "backup	/mnt/storage/containers/plex/config	babushka/plex_config",
            "backup	/mnt/storage/containers/syncthing/config	babushka/syncthing_config",
            "backup	/mnt/storage/containers/syncthing/data/schrodinger	schrodinger/",
            "backup	/mnt/storage/containers/transmission/data/transmission-home	babushka/transmission_home",
            "backup	/mnt/storage/containers/unifi/data	babushka/unifi_data",
            "backup	/mnt/storage/documents	babushka/",
            "backup	/mnt/storage/media/videos/movies/library	babushka/",
            "backup	/mnt/storage/media/videos/tv/library	babushka/"
          ],
        }
      ],
      tags: [
        "local.module.rsnapshot"
      ]
    }

  - { role: local.module.dma,
      smarthost: localhost,
      tags: [
        "local.module.dma"
      ]
    }

  - { role: stuvusit.smartd,
      smartd_devices: {
        /dev/disk/by-uuid/4b8b3527-618c-416c-8f21-a232d750fdae: {
          mail_recipients: [ "{{ vault_smartd_mail | trim }}" ],
          type: "sat",
        },
        /dev/disk/by-uuid/bd1d7435-d413-49dd-be44-c7f18ea1bb49: {
          mail_recipients: [ "{{ vault_smartd_mail | trim }}" ],
          type: "sat",
        },
      },
      tags: [
        "stuvusit.smartd"
      ]
    }

  - { role: jnv.unattended-upgrades,
      unattended_mail: '{{ vault_unattended_mail | trim }}',
      unattended_mail_only_on_error: true,
      unattended_remove_unused_dependencies: true,
      unattended_update_days: '{"Sat";"Sun"}',
      unattended_automatic_reboot_time: '06:00',
      tags: [
        "jnv.unattended-upgrades"
      ]
    }

  - { role: dev-sec.ansible-ssh-hardening,
      os_auth_lockout_time:        60,
      os_auth_pam_passwdqc_enable: false,
      sftp_enabled:                true,
      ssh_allow_agent_forwarding:  true,
      ssh_allow_tcp_forwarding:    "yes",
      ssh_banner:                  true,
      ssh_max_auth_retries:        5,  # should we remove this, i have too many keys :(
      ssh_use_pam:                 true,  # to allow login via locked accounts, i.e. no passwords
      tags: [
        "dev-sec.ansible-ssh-hardening"
      ]
    }

  - { role: dev-sec.ansible-os-hardening,
      tags: [
        "dev-sec.ansible-os-hardening"
      ]
    }
