galaxy_info:
  author: 
  description: Host specific role for Babushka
  company: your company (optional)

  # If the issue tracker for your role is not on github, uncomment the
  # next line and provide a value
  # issue_tracker_url: http://example.com/issue/tracker

  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: GPLv3

  min_ansible_version: 2.4

  # If this a Container Enabled role, provide the minimum Ansible Container version.
  # min_ansible_container_version:

  # Optionally specify the branch Galaxy will use when accessing the GitHub
  # repo for this role. During role install, if no tags are available,
  # Galaxy will use this branch. During import Galaxy will access files on
  # this branch. If Travis integration is configured, only notifications for this
  # branch will be accepted. Otherwise, in all cases, the repo's default branch
  # (usually master) will be used.
  #github_branch:

  #
  # platforms is a list of platforms, and each platform has a name and a list of versions.
  #
  # platforms:
  # - name: Fedora
  #   versions:
  #   - all
  #   - 25
  # - name: SomePlatform
  #   versions:
  #   - all
  #   - 1.0
  #   - 7
  #   - 99.99

  galaxy_tags: []
    # List tags for your role here, one per line. A tag is a keyword that describes
    # and categorizes the role. Users find roles by searching for tags. Be sure to
    # remove the '[]' above, if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of alphanumeric characters.
    #       Maximum 20 tags per role.

dependencies:
  - { role: local.ansible-pull,
      tags: [
        "ansible-pull",
        "local.ansible-pull"
      ]
    }

  - { role: local.ssh-authorised-keys,
      tags: [
        "ssh-authorised-keys",
        "local.ssh-authorised-keys"
      ]
    }

  - { role: local.sshd-banner,
      tags: [
        "sshd-banner",
        "local.sshd-banner"
      ]
    }

  - { role: local.papertrail-logging,
      tags: [
        "papertrail-logging",
        "local.papertrail-logging"
      ]
    }

  - { role: dev-sec.ansible-ssh-hardening,
      os_auth_lockout_time:        60,
      os_auth_pam_passwdqc_enable: false,
      sftp_enabled:                true,
      ssh_allow_agent_forwarding:  true,
      ssh_allow_tcp_forwarding:    true,
      ssh_banner:                  true,
      ssh_max_auth_retries:        5,  # should we remove this, i have too many keys :(
      ssh_use_pam:                 true,  # to allow login via locked accounts, i.e. no passwords
      tags: [
        "ansible-ssh-hardening",
        "dev-sec.ansible-ssh-hardening"
      ]
    }

  - { role: dev-sec.ansible-os-hardening,
      tags: [
        "ansible-os-hardening",
        "dev-sec.ansible-os-hardening"
      ]
    }

  - { role: local.docker-compose,
      compose_project_name: "babuskha",
      domain_name:          "{{ vault_domain_name | trim }}",
      email_address:        "{{ vault_email_address | trim }}",
      oauth2_client_id:     "{{ vault_oauth2_client_id | trim }}",
      oauth2_client_secret: "{{ vault_oauth2_client_secret | trim }}",
      oauth2_cookie_secret: "{{ vault_oauth2_cookie_secret | trim }}",
      openvpn_config:       "{{ vault_openvpn_config | trim }}",
      openvpn_password:     "{{ vault_openvpn_password | trim }}",
      openvpn_provider:     "{{ vault_openvpn_provider | trim }}",
      openvpn_username:     "{{ vault_openvpn_username | trim }}",
      radarr_apikey:        "{{ vault_radarr_apikey | trim }}",
      samba_user1:          "{{ vault_samba_user1 | trim }}",
      samba_user2:          "{{ vault_samba_user2 | trim }}",
      smtp_gmail_password:  "{{ vault_smtp_gmail_password | trim }}",
      smtp_gmail_user:      "{{ vault_smtp_gmail_user | trim }}",
      smtp_hostname:        "{{ vault_smtp_hostname | trim }}",
      smtp_mailname:        "{{ vault_smtp_mailname | trim }}",
      tags: [
        "docker-compose",
        "local.docker-compose"
      ]
    }
