---
# tasks file for local.docker-compose
- name: "Create directories"
  file:
    path: "/root/{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default(0750) }}"
  with_items:
    - path: docker-compose
    - path: docker-compose/mbsync
    - path: docker-compose/monitoring
    - path: docker-compose/monitoring/alertmanager
    - path: docker-compose/monitoring/prometheus
  tags:
    - tasks
    - docker
    - docker-compose
    - directories
    - monitoring
    - backups

- name: "Checkout dockprom repository"
  git:
    repo: "https://github.com/stefanprodan/dockprom.git"
    dest: /root/docker-compose/monitoring/dockprom
    version: v3.23.2
  tags:
    - tasks
    - docker
    - docker-compose
    - monitoring

- name: "Template files"
  template:
    src: "templates/{{ item.src }}"
    dest: "/root/docker-compose/{{ item.dest }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default(0644) }}"
  with_items:
    - src: authenticated-emails.conf.j2
      dest: authenticated-emails.conf
    - src: docker-compose.j2.env
      dest: .env
    - src: index-private.j2.html
      dest: index-private.html
    - src: index-public.j2.html
      dest: index-public.html
    - src: mbsync/mbsyncrc.j2
      dest: mbsync/mbsyncrc
    - src: monitoring/alertmanager/config.yml.j2
      dest: monitoring/alertmanager/config.yml
    - src: nginx-private.j2.conf
      dest: nginx-private.conf
    - src: nginx-public.j2.conf
      dest: nginx-public.conf
    - src: ssmtp.j2.conf
      dest: ssmtp.conf
  tags:
    - tasks
    - docker
    - docker-compose
    - monitoring
    - alertmanager
    - mbsync
    - nginx
    - ssmtp

- name: "Copy files"
  copy:
    src: "files/{{ item.src }}"
    dest: "/root/docker-compose/{{ item.dst | default(item.src) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
    mode: "{{ item.mode | default(0644) }}"
  with_items:
    - src: docker-compose.yml
    - src: mbsync/crontab
    - src: monitoring/prometheus/alert.rules
    - src: monitoring/prometheus/prometheus.yml
    - src: post-processing.sh
      mode: "0755"
  tags:
    - tasks
    - docker
    - docker-compose
    - monitoring
    - prometheus
