---
# tasks file for babushka
- name: "install packages (main group)"
  apt:
    name:
      - bmon
      - collectl
      - ferm
      - htop
      - iftop
      - iotop
      - iptraf
      - nethogs
      - nmap
      - rsnapshot
      - strace
      - sysstat
      - systemtap
    state: present
  tags:
    - babushka
    - tasks
    - system
    - packages

- name: "Mount storage"
  mount:
    name: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.type | default('ext4') }}"
    opts: "{{ item.opts | default('defaults') }}"
    dump: "{{ item.dump | default(0) }}"
    passno: "{{ item.passno | default (2) }}"
    state: present
  with_items: "{{ mounts }}"
  when: mounts is defined
  tags:
    - babushka
    - tasks
    - system
    - storage
    - mount
