---
# tasks file for babushka
- name: "install packages (main group)"
  apt:
    name:
      - bmon
      - collectl
      - ferm
      - htop
      - iftop
      - iotop
      - iptraf
      - nethogs
      - nmap
      - rsnapshot
      - strace
      - sysstat
      - systemtap
    state: present
  tags:
    - babushka
    - tasks
    - system
    - packages

- name: "Mount storage"
  mount:
    name: "{{ item.path }}"
    src: "{{ item.source }}"
    fstype: "{{ item.type | default('ext4') }}"
    opts: "{{ item.opts | default('defaults') }}"
    dump: "{{ item.dump | default(0) }}"
    passno: "{{ item.passno | default (2) }}"
    state: present
  with_items: "{{ mounts }}"
  when: mounts is defined
  tags:
    - babushka
    - tasks
    - system
    - storage
    - mount

- name: "docker-compose folder"
  file:
    path: /root/docker-compose
    state: directory
    owner: root
    group: root
    mode: 0750
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose

- name: "authenticated-emails.conf"
  copy:
    content: "{{ email_address }}"
    dest: /root/docker-compose/authenticated-emails.conf
    owner: root
    group: root
    mode: 0400
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose
    - oauth2_proxy

- name: "docker-compose .env"
  template:
    src: templates/docker-compose.env.j2
    dest: /root/docker-compose/.env
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose

- name: "docker-compose.yml"
  template:
    src: templates/docker-compose.yml.j2
    dest: /root/docker-compose/docker-compose.yml
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose

- name: "nginx private index.html"
  template:
    src: templates/index-private.html.j2
    dest: /root/docker-compose/index-private.html
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose

- name: "nginx private config"
  template:
    src: templates/nginx-private.conf.j2
    dest: /root/docker-compose/nginx-private.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose
    - private
    - nginx

- name: "nginx public index.html"
  template:
    src: templates/index-public.html.j2
    dest: /root/docker-compose/index-public.html
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose

- name: "nginx public config"
  template:
    src: templates/nginx-public.conf.j2
    dest: /root/docker-compose/nginx-public.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose
    - public
    - nginx

- name: "ssmtp.conf file"
  template:
    src: templates/ssmtp.conf.j2
    dest: /root/docker-compose/ssmtp.conf
    owner: root
    group: root
    mode: 0644
  tags:
    - babushka
    - tasks
    - docker
    - docker-compose
