{
 "title": "Internet Connection Health",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Traffic Lights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Probes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-http\"}"
    }
   ]
  },
  {
   "title": "DNS Probes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=~\"blackbox-dns-.*\", instance=~\"1.*|8.*\"}"
    }
   ]
  },
  {
   "title": "TCP Probes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-tcp\"}"
    }
   ]
  },
  {
   "title": "ICMP Probes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox-icmp\"}"
    }
   ]
  },
  { "title": "Detailed Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Speedtest Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps", "label": "Data speed" }
   ],
   "targets": [
    {
     "expr": "speedtest_download_bytes*8",
     "legendFormat": "speedtest_download_bytes{instance=\"{{instance}}\", job=\"{{job}}\"}"
    },
    {
     "expr": "speedtest_upload_bytes*8",
     "legendFormat": "speedtest_upload_bytes{instance=\"{{instance}}\", job=\"{{job}}\"}"
    }
   ]
  },
  {
   "title": "Speedtest Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "expr": "speedtest_latency_ms" },
    { "expr": "speedtest_jittter_ms" }
   ]
  },
  {
   "title": "DNS Request Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "probe_dns_duration_seconds{phase=\"connect\"}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "probe_http_duration_seconds{phase=\"connect\"}"
    }
   ]
  },
  {
   "title": "TCP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox-tcp\"}"
    }
   ]
  },
  {
   "title": "ICMP Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms", "label": "Duration" }
   ],
   "targets": [
    {
     "expr": "probe_duration_seconds{job=\"blackbox-icmp\"}"
    }
   ]
  },
  {
   "title": "Probe Health",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "probe_success" }
   ]
  }
 ]
}